### ISSUE TITLE
TealDryRun.execute() throws exception from okhttp library for Atomic Trasaction with a payment transaction

### ISSUE THREAD

**Issue by satran004** [algorand/java-algorand-sdk#199]
SDK version: 1.5.1

I am trying to DryRun an atomic transaction with two transactions.

1. Stateful contract transaction
2. Payment transaction (regular transfer)

The transaction posting is working as expected for this atomic transaction. (After grouping and signing individual transactions)

But when I try to **DryRun** this transaction using **TealDryRun.execute** api, I am getting "unexpected end of stream" exception from okhttp library. It doesn't return a proper error message.

This happens only when I have a **regular payment transaction** in the group and I try to do DryRun.

But a group with mix of stateful contracts or stateful and logisig stateless transactions works as expected.

Stacktrace:

java.io.IOException: unexpected end of stream on com.squareup.okhttp.Address@bb4ea06b
	at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:201)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
	at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)
	at com.squareup.okhttp.Call.getResponse(Call.java:287)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
	at com.algorand.algosdk.v2.client.common.Client.executeCall(Client.java:112)
	at com.algorand.algosdk.v2.client.common.Query.baseExecute(Query.java:27)
	at com.algorand.algosdk.v2.client.algod.TealDryrun.execute(TealDryrun.java:56)

**Comment by ian-algorand** [comment]
Investigation is needed to figure out why this is happening.

**Comment by jsgranados** [comment]
Closing this. Seems outdated and dryrun has been replaced with simulate.
