### ISSUE TITLE
Error: Transaction not confirmed after 10 rounds

### ISSUE THREAD

**Issue by rohit-gandhe** [algorand/java-algorand-sdk#276]
### Can't get code to work from this link: https://developer.algorand.org/docs/sdks/java/

I am trying the tutorial on the page above and everything seems to work - The docker sandbox is up and running, the client connects and prints the balance correctly, but the transaction doesn't go through.

``` 
My Address: RGXU3ARHXQ7Y3Z2CLODR7AQVGWAAQ5PWMUOP2ZP5MRMRRYZLCUAXEK326E
My Passphrase: redacted

Account Balance: 30000000 microAlgos
Algorand suggested parameters: {
  "genesis-hash": "SGO1GKSzyE7IEPItTxCByw9x8FmnrCDexi9/cOUJOiI=",
  "min-fee": 1000,
  "consensus-version": "https://github.com/algorandfoundation/specs/tree/bc36005dbd776e6d1eaf0c560619bb183215645c",
  "fee": 0,
  "genesis-id": "testnet-v1.0",
  "last-round": 18087203
}
java.lang.Exception: Transaction not confirmed after 10 rounds!
	at GettingStarted.waitForConfirmation(GettingStarted.java:146)
	at GettingStarted.gettingStartedExample(GettingStarted.java:78)
	at GettingStarted.main(GettingStarted.java:152)
```

### Your environment
Mac
JDK 11

### Steps to reproduce

1. run docker image using `./sandbox up testnet`
2. Run the java example on this page: https://developer.algorand.org/docs/sdks/java/

### Expected behaviour
The transaction should transfer funds between accounts

### Actual behaviour
Transaction times out after 10 tries

**Comment by rohit-gandhe** [comment]
Never mind, user error!
